// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLPQcXDDoZ1FB-tLEeZhWGvlR6qkaLXGg',
    appId: '1:547795158340:web:4424db6c6a20f35c6d8311',
    messagingSenderId: '547795158340',
    projectId: 'collegehub-711d5',
    authDomain: 'collegehub-711d5.firebaseapp.com',
    storageBucket: 'collegehub-711d5.firebasestorage.app',
    measurementId: 'G-969J9CH1ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-QzzdJQIUGP38xmCg_PhK3D7_aM_lNSo',
    appId: '1:547795158340:android:0e2452ff915778fd6d8311',
    messagingSenderId: '547795158340',
    projectId: 'collegehub-711d5',
    storageBucket: 'collegehub-711d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiX-vf0CzukwEtFGnSNLzSpI0GrmJzVok',
    appId: '1:547795158340:ios:c1df0a4cb58de4a96d8311',
    messagingSenderId: '547795158340',
    projectId: 'collegehub-711d5',
    storageBucket: 'collegehub-711d5.firebasestorage.app',
    iosClientId: '547795158340-h07iuu7n65niiavbfrrvskfmretji1kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.collegehub',
  );
}
